# Generated by Django 5.1.1 on 2024-10-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=244, verbose_name='Автор'),
        ),
    ]
